### PR TITLE
Point to updated fixtures repo

### PR DESCRIPTION
**Pull request by GretaCB**
cc @springmeyer @mapsam

### CODE REVIEW

**Review by mapsam — APPROVED** [review]
thanks @GretaCB!

**Comment by springmeyer** [comment]
👍

**Comment by springmeyer** [comment]
oh my goodness. totally forgot about this and just created https://github.com/mapbox/mvt-bench-fixtures/pull/3. How about we merge https://github.com/mapbox/mvt-bench-fixtures/pull/3 since it is a little more explicit?

**Comment by GretaCB** [comment]
@springmeyer sounds good! I totally forgot about this PR

**Comment by springmeyer** [comment]
Merged #3 just now. Sorry for missing this one earlier. Will close now.

**Pull request closed without merging**
